### ISSUE TITLE
Unable to create ops Manager on Kubernetes

### ISSUE THREAD

**Issue by Techshubh** [mongodb/mongodb-enterprise-kubernetes#99] opened 2020-05-11 09:44 UTC
Hi,

I'm Unable to deploy instance of ops Manager on Kubernetes.

Below the yml file configuration i'm using.

````
---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager-external
spec:
  replicas: 1
  version: 4.2.12
  adminCredentials: opsmanager-admin

  //optional. Disabled by default. Creates an additional service to make Ops Manager reachable from
   //outside of the Kubernetes cluster.
  externalConnectivity:
    # LoadBalancer|NodePort
    type: LoadBalancer

  applicationDatabase:
    members: 3
    version: 4.2.6-ent
    persistent: true
````
And Apply the command

`oc apply -f ops-manager-external.yaml `

And check the status

`oc get om`
```

NAME                   REPLICAS   VERSION   STATE (OPSMANAGER)   STATE (APPDB)   STATE (BACKUP)   AGE       WARNINGS
ops-manager-external   1          4.2.12                                                          3s
```

Also 
`oc get om -o yaml -w`

```
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"mongodb.com/v1","kind":"MongoDBOpsManager","metadata":{"annotations":{},"name":"ops-manager-external","namespace":"mongodb"},"spec":{"adminCredentials":"opsmanager-admin","applicationDatabase":{"members":3,"persistent":true,"version":"4.2.6-ent"},"externalConnectivity":{"type":"LoadBalancer"},"replicas":1,"version":"4.2.12"}}
  creationTimestamp: 2020-05-11T10:03:49Z
  generation: 1
  name: ops-manager-external
  namespace: mongodb
  resourceVersion: "105580583"
  selfLink: /apis/mongodb.com/v1/namespaces/mongodb/opsmanagers/ops-manager-external
  uid: b5be585e-936e-11ea-9112-000d3a7be27f
spec:
  adminCredentials: opsmanager-admin
  applicationDatabase:
    members: 3
    persistent: true
    version: 4.2.6-ent
  externalConnectivity:
    type: LoadBalancer
  replicas: 1
  version: 4.2.12
```

Unable to debug as i got no error or issue.
Neither pods are created on my openshift

Only thing that is generated was ops manager db password in secret.

Please help me

**Comment by antonlisovenko** [comment] 2020-05-11 11:22
hi @Techshubh 
thanks for your report

Could you show the Operator logs please?
`kubectl logs deployment/mongodb-enterprise-operator`

**Comment by Techshubh** [comment] 2020-05-11 11:26
Here the logs

```
{"level":"info","ts":1589187776.3489435,"caller":"ops-manager-kubernetes/main.go:169","msg":"Operator environment: prod"}
{"level":"info","ts":1589187776.349406,"caller":"ops-manager-kubernetes/main.go:170","msg":"Operator version: 1.5.2"}
{"level":"info","ts":1589187776.3494241,"caller":"ops-manager-kubernetes/main.go:171","msg":"Go Version: go1.13.8"}
{"level":"info","ts":1589187776.3494608,"caller":"ops-manager-kubernetes/main.go:172","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1589187776.3494763,"caller":"envutil/envutil.go:40","msg":"Environment variables:"}
{"level":"info","ts":1589187776.3498576,"caller":"envutil/envutil.go:46","msg":"BACKUP_WAIT_RETRIES=30"}
{"level":"info","ts":1589187776.3498774,"caller":"envutil/envutil.go:46","msg":"BACKUP_WAIT_SEC=3"}
{"level":"info","ts":1589187776.349904,"caller":"envutil/envutil.go:46","msg":"IMAGE_PULL_SECRETS=openshift-pull-secret"}
{"level":"info","ts":1589187776.349943,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT=tcp://172.30.0.1:443"}
{"level":"info","ts":1589187776.3499794,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_443_TCP=tcp://172.30.0.1:443"}
{"level":"info","ts":1589187776.350001,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_443_TCP_ADDR=172.30.0.1"}
{"level":"info","ts":1589187776.3500133,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_443_TCP_PORT=443"}
{"level":"info","ts":1589187776.3500388,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_443_TCP_PROTO=tcp"}
{"level":"info","ts":1589187776.350105,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_53_TCP=tcp://172.30.0.1:53"}
{"level":"info","ts":1589187776.350131,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_53_TCP_ADDR=172.30.0.1"}
{"level":"info","ts":1589187776.35018,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_53_TCP_PORT=53"}
{"level":"info","ts":1589187776.3502264,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_53_TCP_PROTO=tcp"}
{"level":"info","ts":1589187776.3502533,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_53_UDP=udp://172.30.0.1:53"}
{"level":"info","ts":1589187776.3502712,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_53_UDP_ADDR=172.30.0.1"}
{"level":"info","ts":1589187776.3502967,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_53_UDP_PORT=53"}
{"level":"info","ts":1589187776.3503523,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_53_UDP_PROTO=udp"}
{"level":"info","ts":1589187776.3503928,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_SERVICE_HOST=172.30.0.1"}
{"level":"info","ts":1589187776.350421,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_SERVICE_PORT=443"}
{"level":"info","ts":1589187776.350471,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_SERVICE_PORT_DNS=53"}
{"level":"info","ts":1589187776.3505023,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_SERVICE_PORT_DNS_TCP=53"}
{"level":"info","ts":1589187776.3505392,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_SERVICE_PORT_HTTPS=443"}
{"level":"info","ts":1589187776.350571,"caller":"envutil/envutil.go:46","msg":"MANAGED_SECURITY_CONTEXT=true"}
{"level":"info","ts":1589187776.350578,"caller":"envutil/envutil.go:46","msg":"MONGODB_ENTERPRISE_DATABASE_IMAGE=registry.connect.redhat.com/mongodb/enterprise-database:1.5.2"}
{"level":"info","ts":1589187776.3505902,"caller":"envutil/envutil.go:46","msg":"OPERATOR_ENV=prod"}
{"level":"info","ts":1589187776.3505964,"caller":"envutil/envutil.go:46","msg":"OPS_MANAGER_IMAGE_PULL_POLICY=Always"}
{"level":"info","ts":1589187776.3506112,"caller":"envutil/envutil.go:46","msg":"OPS_MANAGER_IMAGE_REPOSITORY=registry.connect.redhat.com/mongodb/mongodb-enterprise-ops-manager"}
{"level":"info","ts":1589187776.3506362,"caller":"envutil/envutil.go:46","msg":"WATCH_NAMESPACE=mongodb"}
{"level":"info","ts":1589187777.058295,"caller":"ops-manager-kubernetes/main.go:96","msg":"Registering Components."}
{"level":"info","ts":1589187777.8270311,"caller":"operator/mongodbstandalone_controller.go:65","msg":"Registered controller mongodbstandalone-controller"}
{"level":"info","ts":1589187777.8274462,"caller":"operator/mongodbreplicaset_controller.go:189","msg":"Registered controller mongodbreplicaset-controller"}
{"level":"info","ts":1589187777.8274953,"caller":"operator/mongodbshardedcluster_controller.go:405","msg":"Registered controller mongodbshardedcluster-controller"}
{"level":"info","ts":1589187777.827876,"caller":"operator/mongodbopsmanager_controller.go:229","msg":"Registered controller opsmanager-controller"}
{"level":"info","ts":1589187777.8280048,"caller":"operator/mongodbuser_controller.go:221","msg":"Registered controller mongodbuser-controller"}
{"level":"info","ts":1589187777.8280268,"caller":"ops-manager-kubernetes/main.go:112","msg":"Registered CRD: mongodb"}
{"level":"info","ts":1589187777.8280587,"caller":"ops-manager-kubernetes/main.go:112","msg":"Registered CRD: opsmanagers"}
{"level":"info","ts":1589187777.828102,"caller":"ops-manager-kubernetes/main.go:112","msg":"Registered CRD: mongodbusers"}
{"level":"info","ts":1589187777.8281598,"caller":"ops-manager-kubernetes/main.go:115","msg":"Starting the Cmd."}
{"level":"info","ts":1589188862.5139663,"caller":"operator/mongodbopsmanager_controller.go:72","msg":"-> OpsManager.Reconcile","OpsManager":"mongodb/ops-manager"}
{"level":"info","ts":1589188862.5140412,"caller":"operator/mongodbopsmanager_controller.go:73","msg":"OpsManager.Spec","OpsManager":"mongodb/ops-manager","spec":{"configuration":{"mms.fromEmailAddr":"admin@thecompany.com"},"version":"4.2.12","replicas":3,"clusterDomain":"mycompany.net","adminCredentials":"ops-manager-admin-secret","applicationDatabase":{"version":"4.2.6-ent","clusterDomain":"mycompany.net","persistent":true,"type":"ReplicaSet","members":3,"podSpec":{"cpu":"0.25"},"security":{"tls":{"secretRef":{}},"authentication":{"enabled":false,"modes":["SCRAM"]}}},"backup":{"enabled":true}}}
{"level":"info","ts":1589188862.514124,"caller":"operator/mongodbopsmanager_controller.go:74","msg":"OpsManager.Status","OpsManager":"mongodb/ops-manager","status":{"opsManager":{"phase":""},"applicationDatabase":{"phase":"","version":"","type":""},"backup":{"phase":""}}}
{"level":"info","ts":1589188862.5142443,"caller":"operator/mongodbopsmanager_controller.go:402","msg":"Creating mongodb-ops-manager password in secret/ops-manager-db-password in namespace mongodb","OpsManager":"mongodb/ops-manager"}
{"level":"error","ts":1589188862.5404124,"caller":"operator/common_controller.go:271","msg":"Error updating status to Reconciling: the server rejected our request due to an error in our request","ReplicaSet (AppDB)":"mongodb/ops-manager-db","stacktrace":"github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileCommonController).updateStatus\n\t/data/mci/b8bf4462e6c62808e527f1b62485f838/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/common_controller.go:271\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileAppDbReplicaSet).Reconcile\n\t/data/mci/b8bf4462e6c62808e527f1b62485f838/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/appdbreplicaset_controller.go:43\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*OpsManagerReconciler).Reconcile\n\t/data/mci/b8bf4462e6c62808e527f1b62485f838/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbopsmanager_controller.go:97\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/data/mci/b8bf4462e6c62808e527f1b62485f838/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/data/mci/b8bf4462e6c62808e527f1b62485f838/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/data/mci/b8bf4462e6c62808e527f1b62485f838/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/data/mci/b8bf4462e6c62808e527f1b62485f838/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/data/mci/b8bf4462e6c62808e527f1b62485f838/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/data/mci/b8bf4462e6c62808e527f1b62485f838/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1589188863.541242,"caller":"operator/mongodbopsmanager_controller.go:72","msg":"-> OpsManager.Reconcile","OpsManager":"mongodb/ops-manager"}
{"level":"info","ts":1589188863.5413022,"caller":"operator/mongodbopsmanager_controller.go:73","msg":"OpsManager.Spec","OpsManager":"mongodb/ops-manager","spec":{"configuration":{"mms.fromEmailAddr":"admin@thecompany.com"},"version":"4.2.12","replicas":3,"clusterDomain":"mycompany.net","adminCredentials":"ops-manager-admin-secret","applicationDatabase":{"version":"4.2.6-ent","clusterDomain":"mycompany.net","persistent":true,"type":"ReplicaSet","members":3,"podSpec":{"cpu":"0.25"},"security":{"tls":{"secretRef":{}},"authentication":{"enabled":false,"modes":["SCRAM"]}}},"backup":{"enabled":true}}}
{"level":"info","ts":1589188863.541423,"caller":"operator/mongodbopsmanager_controller.go:74","msg":"OpsManager.Status","OpsManager":"mongodb/ops-manager","status":{"opsManager":{"phase":""},"applicationDatabase":{"phase":"","version":"","type":""},"backup":{"phase":""}}}
```

**Comment by Techshubh** [comment] 2020-05-11 11:30
@antonlisovenko 

I'm using the latest operator version 1.5.2.

**Comment by antonlisovenko** [comment] 2020-05-11 16:49
@Techshubh seems we cannot reproduce this in Minishift
Do you have access to the API server logs to see what is happening there?
Can you show the output from `kubectl version` please?

**Comment by Techshubh** [comment] 2020-05-11 18:31
Yeah. I will share output. Need to contact to my devOps team. 
I don't know how to access them.

Can you please tell till what time you will available ?.

Thanks

**Comment by Techshubh** [comment] 2020-05-12 06:35
Here the output for 

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-07-10T16:40:58Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Techshubh** [comment] 2020-05-12 06:39
@Techshubh 

I do have access but can you please tell me which command required or where i can find them -- API Server Logs

**Comment by antonlisovenko** [comment] 2020-05-12 09:54
@Techshubh 
after looking again at the stacktrace I have a hypothesis that you won't see much there as the error says that the API server has rejected the request (though if you find something valuable there - this may help)

Just to confirm - have you created the CRDs without `subresources` section?

I think I have an idea what could be fixed in the code to handle this.
So far - can you try 1.4.5 Operator please?

**Comment by Techshubh** [comment] 2020-05-12 09:59
@antonlisovenko 

Yes. I have created CRDs without `subresources `section

I already tried 1.4.5 operator thing  and it is working for me but i need to do this work on production environment. As per the release ops Manager for production environment comes with operator 1.5.0 + version.

 so you will be doing changes in the code to code handle this ?

Thanks for the support.

**Comment by Techshubh** [comment] 2020-05-12 10:00
@antonlisovenko 
can you please be specific for the api server logs. As i asked before 
Command i'm using is right or wrong ?

**Comment by antonlisovenko** [comment] 2020-05-12 12:03
> @antonlisovenko
> can you please be specific for the api server logs. As i asked before
> Command i'm using is right or wrong ?

Not sure I know.

@Techshubh can you please try the non-release Operator:
```
image: quay.io/mongodb/mongodb-enterprise-operator-ubi-prerelease:5eba7a733e8e867cc29b748a
```
tell me if the issue is gone

**Comment by Techshubh** [comment] 2020-05-12 12:18
@antonlisovenko 

Nope , the issue is not gone. I changed the image as per you request and again deploy the operator
But there is changes in logs

```
{"level":"info","ts":1589285553.4349213,"caller":"operator/mongodbopsmanager_controller.go:72","msg":"-> OpsManager.Reconcile","OpsManager":"mongodb/ops-manager-external"}
{"level":"info","ts":1589285553.4349675,"caller":"operator/mongodbopsmanager_controller.go:73","msg":"OpsManager.Spec","OpsManager":"mongodb/ops-manager-external","spec":{"version":"4.2.6","replicas":1,"adminCredentials":"opsmanager-admin","applicationDatabase":{"version":"4.2.6-ent","clusterDomain":"cluster.local","persistent":true,"type":"ReplicaSet","members":3,"podSpec":{},"security":{"tls":{"secretRef":{}},"authentication":{"enabled":false,"modes":["SCRAM"]}}},"backup":{"enabled":true}}}
{"level":"info","ts":1589285553.4350266,"caller":"operator/mongodbopsmanager_controller.go:74","msg":"OpsManager.Status","OpsManager":"mongodb/ops-manager-external","status":{"opsManager":{"phase":""},"applicationDatabase":{"phase":"","version":"","type":""},"backup":{"phase":""}}}
2020/05/12 12:12:33  warn There was an error patching status subresource - trying to patch the whole object (error: the server could not find the requested resource (patch opsmanagers.mongodb.com ops-manager-external))
{"level":"error","ts":1589285553.4469151,"caller":"operator/common_controller.go:272","msg":"Error updating status to Reconciling: the server rejected our request due to an error in our request","ReplicaSet (AppDB)":"mongodb/ops-manager-external-db","stacktrace":"github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileCommonController).updateStatus\n\t/data/mci/7c56c68bbb134209e711a12c6ca3f50d/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/common_controller.go:272\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileAppDbReplicaSet).Reconcile\n\t/data/mci/7c56c68bbb134209e711a12c6ca3f50d/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/appdbreplicaset_controller.go:43\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*OpsManagerReconciler).Reconcile\n\t/data/mci/7c56c68bbb134209e711a12c6ca3f50d/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbopsmanager_controller.go:97\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/data/mci/7c56c68bbb134209e711a12c6ca3f50d/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/data/mci/7c56c68bbb134209e711a12c6ca3f50d/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/data/mci/7c56c68bbb134209e711a12c6ca3f50d/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/data/mci/7c56c68bbb134209e711a12c6ca3f50d/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/data/mci/7c56c68bbb134209e711a12c6ca3f50d/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/data/mci/7c56c68bbb134209e711a12c6ca3f50d/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1589285554.4473557,"caller":"operator/mongodbopsmanager_controller.go:72","msg":"-> OpsManager.Reconcile","OpsManager":"mongodb/ops-manager-external"}
```

New error
`2020/05/12 12:12:33  warn There was an error patching status subresource - trying to patch the whole object (error: the server could not find the requested resource (patch opsmanagers.mongodb.com ops-manager-external))`

Is this something at the mongoDB code or anything i'm doing wrong?

Thanks

**Comment by antonlisovenko** [comment] 2020-05-12 13:38
@Techshubh 
can you please try `quay.io/mongodb/mongodb-enterprise-operator-ubi-prerelease:5ebaa406562343723be6291c`

**Comment by Techshubh** [comment] 2020-05-12 13:53
Changed logs

```
{"level":"info","ts":1589291503.8489487,"caller":"operator/mongodbopsmanager_controller.go:73","msg":"OpsManager.Spec","OpsManager":"mongodb/ops-manager-external","spec":{"version":"4.2.6","replicas":1,"adminCredentials":"opsmanager-admin","applicationDatabase":{"version":"4.2.6-ent","clusterDomain":"cluster.local","persistent":true,"type":"ReplicaSet","members":3,"podSpec":{},"security":{"tls":{"secretRef":{}},"authentication":{"enabled":false,"modes":["SCRAM"]}}},"backup":{"enabled":true}}}
{"level":"info","ts":1589291503.848984,"caller":"operator/mongodbopsmanager_controller.go:74","msg":"OpsManager.Status","OpsManager":"mongodb/ops-manager-external","status":{"opsManager":{"phase":""},"applicationDatabase":{"phase":"","version":"","type":""},"backup":{"phase":""}}}
{"level":"warn","ts":1589291503.8575728,"caller":"operator/common_controller.go:303","msg":"There was an error patching status subresource (seems it's not supported) - trying to patch the whole object (error: the server could not find the requested resource (patch opsmanagers.mongodb.com ops-manager-external))"}
{"level":"error","ts":1589291503.8667777,"caller":"operator/common_controller.go:277","msg":"Error updating status to Reconciling: the server rejected our request due to an error in our request","ReplicaSet (AppDB)":"mongodb/ops-manager-external-db","stacktrace":"github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileCommonController).updateStatus\n\t/data/mci/161cd38d9983ab0faddec4e297beb905/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/common_controller.go:277\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileAppDbReplicaSet).Reconcile\n\t/data/mci/161cd38d9983ab0faddec4e297beb905/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/appdbreplicaset_controller.go:43\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*OpsManagerReconciler).Reconcile\n\t/data/mci/161cd38d9983ab0faddec4e297beb905/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbopsmanager_controller.go:97\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/data/mci/161cd38d9983ab0faddec4e297beb905/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/data/mci/161cd38d9983ab0faddec4e297beb905/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/data/mci/161cd38d9983ab0faddec4e297beb905/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/data/mci/161cd38d9983ab0faddec4e297beb905/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/data/mci/161cd38d9983ab0faddec4e297beb905/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/data/mci/161cd38d9983ab0faddec4e297beb905/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```
Some changed in logs. Still not working

**Comment by Techshubh** [comment] 2020-05-13 10:17
@antonlisovenko 

Any updates ??

**Comment by antonlisovenko** [comment] 2020-05-13 10:22
@Techshubh 
we are still investigating this though it's hard as we don't have a running 3.11 cluster and are using Minishift which works fine.
While we are on it - can you try the `CustomResourceSubresources=true` feature compatibility flag as described in https://v1-15.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ ? Theoretically this could mean that `subresources` should be reenabled in CRDs.

**Comment by Techshubh** [comment] 2020-05-13 11:25
@antonlisovenko 

Last time , i created CRD's by remove the `subs-resources` section from File , now you want to enable through flag.

Is that correct ?

**Comment by antonlisovenko** [comment] 2020-05-13 11:55
@Techshubh 

getting back to you.
I've played with K8s 1.11.0 and seems managed to make Operator work with this version.
So please:
1. ensure no subresources exist in CRDs
2. try the Operator quay.io/mongodb/mongodb-enterprise-operator-ubi-prerelease:5ebaa406562343723be6291c

**Comment by Techshubh** [comment] 2020-05-13 15:11
@antonlisovenko 
Thanks
Now it's Working. Ops Manager deployed Successfully.

This image i can use on production environment ?

**Comment by antonlisovenko** [comment] 2020-05-13 16:30
Glad it worked.
The image passes all the tests in our CI pipeline but it's up to you to decide whether it should be used in production - we don't normally recommend using non-released images in production environment

**Comment by Techshubh** [comment] 2020-05-13 21:08
@antonlisovenko 

So you will be releasing these changes officially on the Red Hat Image Soon ?

**Comment by LouisPlisso** [comment] 2020-05-20 10:58
@Techshubh we will release next week latest, please let us know if this needs to be addressed sooner

**Comment by Techshubh** [comment] 2020-05-23 06:00
@LouisPlisso 
okay. No problem.

Let me know , when it is officially released

**Comment by LouisPlisso** [comment] 2020-06-03 15:05
@Techshubh version 1.5.3 has been released: can you check if your problem is now fixed?

**Closed** 2020-07-08 15:02 UTC
Labels: CLOUDP-62448
