### ISSUE TITLE
Starting ops-manager on Openshift 4.1 results in "permission denied" errors

### ISSUE THREAD

**Issue by Feelas** [mongodb/mongodb-enterprise-kubernetes#37] opened 2019-09-19 09:30 UTC
Issue:
booting up ops-manager on an OpenShift 4.1 cluster results in a failing start & ends up with CrashLoopBackOffed pods.

Log:
`oc logs -f ops-manager-0 -n mongodb
Updating configuration properties file /opt/mongodb/mms/conf/conf-mms.properties
Using property mms.centralUrl=http://ops-manager-svc.mongodb.svc.cluster.local:8080
Using property mms.fromEmailAddr=admin@thecompany.com
Using property mms.managedAppDb=true
Using property mms.temp.appDb.version=4.0.9
Using property mongo.mongoUri=mongodb://ops-manager-db-0.ops-manager-db-svc.mongodb.svc.cluster.local,ops-manager-db-1.ops-manager-db-svc.mongodb.svc.cluster.local,ops-manager-db-2.ops-manager-db-svc.mongodb.svc.cluster.local/?connectTimeoutMS=15000&serverSelectionTimeoutMS=15000
Starting Ops Manager...
Checking the Application Database
chown: changing ownership of '/opt/mongodb/mms/logs/mms0.log': Operation not permitted
[FAILED]
   Check /opt/mongodb/mms/logs/mms0.log for errors
Startup of Ops Manager failed with code 1

mms0.log:

su: must be run from a terminal`

Possible cause (idea):
The container might assume some default UIDs. Since OpenShift uses random UIDs, the chown inside scripts fails.

**Comment by antonlisovenko** [comment] 2019-10-17 09:45
Thanks for your report and sorry for the late response.
We plan to investigate Openshift 4.1 closer to the EOY. So far we only support 3.11

**Comment by komish** [comment] 2019-11-08 22:53
@antonlisovenko is it possible this is just a matter of securityContext?

I see the ability to have the operator manage security contexts through an environment variable ([doc](https://docs.mongodb.com/kubernetes-operator/stable/tutorial/install-k8s-operator/#create-credentials)) but I still end up with an empty security context even with this enabled.

```
oc get statefulsets ops-manager -o json | jq .spec.template.spec.securityContext
{}
```

I tried to manually edit the statefulset, just as a test, but didn't have much luck getting the changes to stick.

Let me know if we can help here. Currently the alm-example in the  CSV that we get via OLM (which deploys a sample of this operand) runs into this issue immediately.

**Comment by antonlisovenko** [comment] 2019-11-11 09:37
Try the latest release of the Operator 1.3.1 - the issue starting the Ops Manager pods as non-root should be fixed so the quay image (based on Ubuntu) should be able to start.
We don't support Rhel base images yet though.

**Comment by komish** [comment] 2019-11-15 20:28
@antonlisovenko thanks for the info. With `MANAGED_SECURITY_CONTEXT` enabled I was able to get the `opsmanager` resource past permissions issues.

I spotted another issue (`mongodb_enterprise_appdb` serviceaccount, role, and rolebindings not created) but this could have been because I modified the existing (read: older version) certified CSV to inject the newer images. I think it best for me to wait for a new certified op to release in case this is already accounted for there before opening an issue.

The remaining question I have is regarding timeline for support on RHEL-based images (and subsequently a new certified op). I'll keep an eye out for details on this. 

Thanks again!

**Comment by antonlisovenko** [comment] 2019-11-18 09:21
hi @komish 
thanks for the feedback.
Hopefully we'll have the Openshift support for OM in the next Operator release (~end of month)

**Comment by theburi** [comment] 2019-11-18 09:27
Hi @komish
Thanking you for running our Operator through a test pass.

Regarding UBI image. Since this feature (Ops Manager CRD) is in Alpha we just released Ubuntu image. However, for our Beta release (scheduled in a few weeks) we will have OpenShift support: UBI image, testing on OS, etc.

**Comment by komish** [comment] 2019-11-18 13:36
@antonlisovenko @theburi Understood! I'll keep an eye out for the beta version. 

> @antonlisovenko: (but again - we'll test it on Openshift 3.11, we haven't worked with 4.2 yet)

Sure, I can do a test pass on my own on 4.x as well. I can't imagine too many discrepancies that need consideration between the two, but if there's anything I spot I can make a note of it for whenever your 4.x testing cycle takes place.

Thanks again for follow up!

**Comment by Feelas** [comment] 2019-11-19 07:29
> hi @komish
> thanks for the feedback.
> Hopefully we'll have the Openshift support for OM in the next Operator release (~end of month)
> (but again - we'll test it on Openshift 3.11, we haven't worked with 4.2 yet)

I've tested 1.3.1 yesterday and Ops Manager runs fine on 4.2, apart from some minor configuration issues.

**Comment by BenElgar** [comment] 2019-11-19 07:46
Excellent—thank you for your feedback, @Feelas!

**Comment by antonlisovenko** [comment] 2019-12-13 15:03
Closing as it was confirmed by the reporter that the issue doesn't exist any more in Openshift 4.2

**Closed by antonlisovenko** 2019-12-13 15:03 UTC
Labels: CLOUDP-52046

**Comment by chechuironman** [comment] 2020-01-29 12:13
guys, 
I have the same problem on Openshift 4.2, I installed from OpenShift operatorhub which have the version 1.2.4
```Updating configuration properties file /mongodb-ops-manager/conf/conf-mms.properties
Using property mms.centralUrl=http://ops-manager-svc.mongodb.svc.cluster.local:8080
Using property mms.fromEmailAddr=admin@thecompany.com
Using property mms.managedAppDb=true
Using property mms.temp.appDb.version=4.0.9
Using property mongo.mongoUri=mongodb://ops-manager-db-0.ops-manager-db-svc.mongodb.svc.cluster.local,ops-manager-db-1.ops-manager-db-svc.mongodb.svc.cluster.local,ops-manager-db-2.ops-manager-db-svc.mongodb.svc.cluster.local/?connectTimeoutMS=15000&serverSelectionTimeoutMS=15000
Starting Ops Manager
Generating new Ops Manager private key...
mkdir: cannot create directory '/mongodb-ops-manager/.mongodb-mms': Permission denied
Failed to create directory /mongodb-ops-manager/.mongodb-mms
Exiting.
Startup of Ops Manager failed with code 1```
